language: node_js
node_js:
  - "4.0"

branches:
  only:
    - master

script:
  - echo "Deploying!"

install:
  - npm install -g firebase-tools

after_success:
  - firebase deploy --token $FIREBASE_API_TOKEN
